# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('working_hours', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='vehicle.Company')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='gender',
            field=models.CharField(choices=[('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleformtype',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type', to='vehicle.VehicleType'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicletype', to='vehicle.VehicleType'),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='vehicle.VehicleType'),
        ),
    ]
