# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20160830_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='vehicleformtype',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='gender',
            new_name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='dealer',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='vehicleformtype',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='vehicleformtype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleformtype',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
        ),
    ]
