# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20160830_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Dealer'},
        ),
        migrations.AlterModelOptions(
            name='vehicleformtype',
            options={'verbose_name': 'Vehicle Form Type'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Vehicle Type'},
        ),
    ]
