# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20160903_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('general_price', models.CharField(blank=True, max_length=20, null=True)),
                ('general_image', models.CharField(blank=True, max_length=20, null=True)),
                ('availability', models.CharField(choices=[('current', 'Current'), ('upcoming', 'Upcoming'), ('discontinued', 'Discontinued')], default='current', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of', to='vehicle.Company')),
                ('vehicle_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_form', to='vehicle.VehicleFormType')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of', to='vehicle.VehicleType')),
            ],
            options={
                'verbose_name': 'Vehicle',
            },
        ),
    ]
