# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20160904_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('seating_capacity', models.CharField(max_length=20)),
                ('tank_capacity', models.CharField(max_length=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='vehicle.Variant')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('length', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('wheelbase', models.CharField(blank=True, max_length=20, null=True)),
                ('bootspace', models.CharField(blank=True, max_length=20, null=True)),
                ('kerbweight', models.CharField(blank=True, max_length=20, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='vehicle.Variant')),
            ],
            options={
                'verbose_name_plural': 'Dimensions',
                'verbose_name': 'Dimension',
            },
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('torque', models.CharField(max_length=20)),
                ('displacement', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('cylinders', models.CharField(max_length=20)),
                ('valvespercyclinder', models.CharField(max_length=20)),
                ('valvemechanism', models.CharField(max_length=20)),
                ('cyclinder_configuration', models.CharField(max_length=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='vehicle.Variant')),
            ],
            options={
                'verbose_name_plural': 'Engines',
                'verbose_name': 'Engine',
            },
        ),
        migrations.CreateModel(
            name='ExteriorFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('keyless_entry', models.CharField(blank=True, max_length=20, null=True)),
                ('rear_wiper', models.CharField(blank=True, max_length=20, null=True)),
                ('rear_sensing_wipers', models.CharField(blank=True, max_length=20, null=True)),
                ('alloy_wheels', models.CharField(blank=True, max_length=20, null=True)),
                ('roof_rails', models.CharField(blank=True, max_length=20, null=True)),
                ('projector_lamp', models.CharField(blank=True, max_length=20, null=True)),
                ('fog_lights', models.CharField(blank=True, max_length=20, null=True)),
                ('moon_roof', models.CharField(blank=True, max_length=20, null=True)),
                ('auto_headlamp', models.CharField(blank=True, max_length=20, null=True)),
                ('steel_rims', models.CharField(blank=True, max_length=20, null=True)),
                ('rear_spoiler', models.CharField(blank=True, max_length=20, null=True)),
                ('chrome_grill', models.CharField(blank=True, max_length=20, null=True)),
                ('daytime_running_lamp', models.CharField(blank=True, max_length=20, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_features', to='vehicle.Variant')),
            ],
            options={
                'verbose_name_plural': 'Exterior features',
                'verbose_name': 'Exterior feature',
            },
        ),
        migrations.CreateModel(
            name='InteriorFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('power_steering', models.CharField(blank=True, max_length=20, null=True)),
                ('power_windows', models.CharField(blank=True, max_length=20, null=True)),
                ('air_cond', models.CharField(blank=True, max_length=20, null=True)),
                ('anti_pinch', models.CharField(blank=True, max_length=20, null=True)),
                ('arm_rest', models.CharField(blank=True, max_length=20, null=True)),
                ('audio_system', models.CharField(blank=True, max_length=20, null=True)),
                ('bluetooth_connectivity', models.CharField(blank=True, max_length=20, null=True)),
                ('cruise_control', models.CharField(blank=True, max_length=20, null=True)),
                ('defogger', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_info_display', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_seat_height_adjust', models.CharField(blank=True, max_length=20, null=True)),
                ('electric_foldable_mirrors', models.CharField(blank=True, max_length=20, null=True)),
                ('electric_mirrors', models.CharField(blank=True, max_length=20, null=True)),
                ('foot_rest', models.CharField(blank=True, max_length=20, null=True)),
                ('keyless_start_stop_button', models.CharField(blank=True, max_length=20, null=True)),
                ('leather_seats', models.CharField(blank=True, max_length=20, null=True)),
                ('power_seats', models.CharField(blank=True, max_length=20, null=True)),
                ('rear_ac_vents', models.CharField(blank=True, max_length=20, null=True)),
                ('remote_boot_relese', models.CharField(blank=True, max_length=20, null=True)),
                ('reversing_camera', models.CharField(blank=True, max_length=20, null=True)),
                ('steering_controls', models.CharField(blank=True, max_length=20, null=True)),
                ('tachometer', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Interior features',
                'verbose_name': 'Interior feature',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehicleformtype',
            options={'verbose_name': 'Vehicle Form Type', 'verbose_name_plural': 'Vehicle Form Types'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
    ]
