# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20160905_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brakes',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='engines',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='exteriorfeatures',
            name='variant',
        ),
        migrations.DeleteModel(
            name='InteriorFeatures',
        ),
        migrations.RemoveField(
            model_name='price',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Brakes',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
        migrations.DeleteModel(
            name='Engines',
        ),
        migrations.DeleteModel(
            name='ExteriorFeatures',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
