# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_roadassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleformtype',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
