# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20160908_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Fuel type', 'verbose_name_plural': 'Fuel type'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variant'},
        ),
        migrations.AlterField(
            model_name='company',
            name='vehicle_type',
            field=models.CharField(choices=[('all', 'All'), ('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='vehicle_type',
            field=models.CharField(choices=[('all', 'All'), ('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('all', 'All'), ('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleformtype',
            name='vehicle_type',
            field=models.CharField(choices=[('all', 'All'), ('car', 'Car'), ('bikes', 'Bikes'), ('trucks', 'Trucks'), ('other', 'Other')], default='car', max_length=10),
        ),
    ]
