# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_roadassistance'),
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('abs', models.CharField(blank=True, max_length=20, null=True)),
                ('airbags', models.CharField(blank=True, max_length=20, null=True)),
                ('immobilizer', models.CharField(blank=True, max_length=20, null=True)),
                ('hill_control', models.CharField(blank=True, max_length=20, null=True)),
                ('central_locking', models.CharField(blank=True, max_length=20, null=True)),
                ('ebd', models.CharField(blank=True, max_length=20, null=True)),
                ('child_safety_lock', models.CharField(blank=True, max_length=20, null=True)),
                ('traction_control', models.CharField(blank=True, max_length=20, null=True)),
                ('hill_descent', models.CharField(blank=True, max_length=20, null=True)),
                ('esp', models.CharField(blank=True, max_length=20, null=True)),
                ('wheel_drive', models.CharField(blank=True, max_length=20, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_features', to='vehicle.Variant')),
            ],
            options={
                'verbose_name_plural': 'Safety features',
                'verbose_name': 'Safety feature',
            },
        ),
    ]
