# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_safetyfeatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteriorFeatures',
        ),
    ]
