# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_roadassistance'),
        ('feature', '0003_delete_interiorfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('power_steering', models.CharField(blank=True, max_length=20, null=True)),
                ('power_windows', models.CharField(blank=True, max_length=20, null=True)),
                ('air_cond', models.CharField(blank=True, max_length=20, null=True)),
                ('anti_pinch', models.CharField(blank=True, max_length=20, null=True)),
                ('arm_rest', models.CharField(blank=True, max_length=20, null=True)),
                ('audio_system', models.CharField(blank=True, max_length=20, null=True)),
                ('bluetooth_connectivity', models.CharField(blank=True, max_length=20, null=True)),
                ('cruise_control', models.CharField(blank=True, max_length=20, null=True)),
                ('defogger', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_info_display', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_seat_height_adjust', models.CharField(blank=True, max_length=20, null=True)),
                ('electric_foldable_mirrors', models.CharField(blank=True, max_length=20, null=True)),
                ('electric_mirrors', models.CharField(blank=True, max_length=20, null=True)),
                ('foot_rest', models.CharField(blank=True, max_length=20, null=True)),
                ('keyless_start_stop_button', models.CharField(blank=True, max_length=20, null=True)),
                ('leather_seats', models.CharField(blank=True, max_length=20, null=True)),
                ('power_seats', models.CharField(blank=True, max_length=20, null=True)),
                ('rear_ac_vents', models.CharField(blank=True, max_length=20, null=True)),
                ('remote_boot_relese', models.CharField(blank=True, max_length=20, null=True)),
                ('reversing_camera', models.CharField(blank=True, max_length=20, null=True)),
                ('steering_controls', models.CharField(blank=True, max_length=20, null=True)),
                ('tachometer', models.CharField(blank=True, max_length=20, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_features', to='vehicle.Variant')),
            ],
            options={
                'verbose_name': 'Interior feature',
                'verbose_name_plural': 'Interior features',
            },
        ),
    ]
