# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_auto_20160909_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyfeatures',
            name='esp',
            field=models.BooleanField(default=False),
        ),
    ]
