# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0006_auto_20160910_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyfeatures',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_features', to='vehicle.Variant'),
        ),
    ]
