# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0003_auto_20160907_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brakes',
            options={'verbose_name': 'Brake', 'verbose_name_plural': 'Brake'},
        ),
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Capacity', 'verbose_name_plural': 'Capacity'},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'verbose_name': 'Dimension', 'verbose_name_plural': 'Dimension'},
        ),
        migrations.AlterModelOptions(
            name='engines',
            options={'verbose_name': 'Engine', 'verbose_name_plural': 'Engine'},
        ),
    ]
